//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tconta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tconta()
        {
            this.textrato = new HashSet<textrato>();
        }
    
        public int IDCONTA { get; set; }
        public int IDCLIENTE { get; set; }
        public string DES_NUMERO { get; set; }
        public string DES_TIPO { get; set; }
        public double VAL_SALDO { get; set; }
    
        public virtual tcliente tcliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<textrato> textrato { get; set; }
    }
}
