//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bancoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcliente()
        {
            this.tconta = new HashSet<tconta>();
        }
    
        public int IDCLIENTE { get; set; }
        public string NOMCLIENTE { get; set; }
        public string NUM_CONTA_CLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tconta> tconta { get; set; }
    }
}
